stages:
  - test
  - build


master:
    stage: build
    only:
        - master
    script:
        - docker build -f dockerfile . -t gitlab.orr.noaa.gov:5002/oillibrary:master
        - docker push gitlab.orr.noaa.gov:5002/oillibrary:master
    tags:
        - shell
        - build

develop:
    stage: build
    only:
        - develop
    script:
        - docker build -f dockerfile . -t gitlab.orr.noaa.gov:5002/oillibrary:develop
        - docker push gitlab.orr.noaa.gov:5002/oillibrary:develop
    tags:
        - shell
        - build

production:
    stage: build
    only:
        - production
    script:
        - docker build -f dockerfile . -t gitlab.orr.noaa.gov:5002/oillibrary:production
        - docker push gitlab.orr.noaa.gov:5002/oillibrary:production
    tags:
        - shell
        - build

test:
    stage: test
    image: registry.orr.noaa.gov/erd/centos-conda
    script:
        - conda install --file conda_requirements.txt
        - python setup.py develop
        - pytest --pyargs oil_library
    tags:
        - docker
