stages:
  - test
  - build


master:
    stage: build
    only:
        - master
    script:
        - docker build -f dockerfile . -t gitlab.orr.noaa.gov:5002/oillibrary
        - docker push gitlab.orr.noaa.gov:5002/oillibrary
    tags:
        - shell
        - build

develop:
    stage: build
    only:
        - develop
    script:
        - docker build -f dockerfile . -t gitlab.orr.noaa.gov:5002/oillibrary:develop
        - docker push gitlab.orr.noaa.gov:5002/oillibrary:develop
    tags:
        - shell
        - build

production:
    stage: build
    only:
        - production
    script:
        - docker build -f dockerfile . -t gitlab.orr.noaa.gov:5002/oillibrary:production
        - docker push gitlab.orr.noaa.gov:5002/oillibrary:production
    tags:
        - shell
        - build

test_develop:
    stage: test
    image: gitlab.orr.noaa.gov:5002/centos-conda
    only:
        - develop
    script:
        - conda install --file conda_requirements.txt
        - python setup.py develop
        - pytest --pyargs oil_library
    except:
        - master
        - production
    tags:
        - docker

