stages:
  - test
  - build


master:
    stage: build
    only:
        - master
    script:
        - docker build -t registry.orr.noaa.gov/gnome/oillibrary:master .
        - docker push registry.orr.noaa.gov/gnome/oillibrary:master
    tags:
        - shell
        - build

develop:
    stage: build
    only:
        - develop
    script:
        - docker build -t registry.orr.noaa.gov/gnome/oillibrary:develop .
        - docker push registry.orr.noaa.gov/gnome/oillibrary:develop
    tags:
        - shell
        - build

production:
    stage: build
    only:
        - production
    script:
        - docker build -t registry.orr.noaa.gov/gnome/oillibrary:production .
        - docker push registry.orr.noaa.gov/gnome/oillibrary:production
    tags:
        - shell
        - build

test:
    stage: test
    image: registry.orr.noaa.gov/erd/centos-conda
    script:
        - conda install --file conda_requirements.txt
        - python setup.py develop
        - pytest --pyargs oil_library
    tags:
        - docker
