master:
    only:
        - master
    script:
        - docker build -f dockerfile . -t gitlab.orr.noaa.gov:5002/oillibrary
        - docker push gitlab.orr.noaa.gov:5002/oillibrary
develop:
    only: 
        - develop
    script:
        - docker build -f dockerfile . -t gitlab.orr.noaa.gov:50002/oillibrary:develop
        - docker push gitlab.orr.noaa.gov:5002/oillibrary:develop
